### ISSUE TITLE
just want to ask questions

### ISSUE THREAD

**Issue by lokifrit** [bryanbibat/karaoke#1]
Where are you getting most of the list of your songs, specially the ones from TJ media?

**Comment by bryanbibat** [comment]
For Chinese, Japanese, Korean songs, you can get the TJ Media list from local distributor (Soundmax in Raon) for ~P250, Kumyoung from the [link](http://dncenter.ikaraoke.kr/) in the About page, and for Platinum, you can download it from their website (sign-up required).

For English and Tagalog, there are a lot of Google-able lists out there. Platinum also has an Android app.
